### ISSUE TITLE
finish security-manager integration

### ISSUE THREAD

**Issue by pohly** [01org/meta-intel-iot-security#16]
It currently runs, but is probably not very usable.

From the initial commit:

```
commit a6f28157febdc0a47593b85eb5fbb21029453ea0
Author: Patrick Ohly <patrick.ohly@intel.com>
Date:   Tue Mar 24 06:38:10 2015 -0700

    security-manager: initial recipe

    Service starts, but the recipe needs further work:
    - Location of database under /usr/dbspace is hard-coded
      in the recipe. Should be taken from a distro conf variable
      by this recipe and tizen-platform-conf.
    - Setting Smack labels in postinst does not seem to
      have an effect.
```

We also need tests.

**Comment by pohly** [comment]
Furthermore, does this have to run as root?

**Comment by johnwhiteman** [comment]
So this discussed on a different thread, but will we want to ultimately want use https://github.com/Samsung/security-manager once it is populated?

**Comment by pohly** [comment]
On Tue, 2015-05-26 at 15:03 -0700, johnwhiteman wrote:

> So this discussed on a different thread, but will we want to
> ultimately want use https://github.com/Samsung/security-manager once
> it is populated?

Yes.

**Comment by jobol** [comment]
Is it possible to switch to 1.1.0 of security-manager? It maybe need vasum but maybe not.

**Comment by pohly** [comment]
@jobol a patch updating security-manager to 1.1.0 would be welcome.

**Comment by jobol** [comment]
hum. I'll look at it soon. don't hesitate to ask for progresses if I'm muted

**Comment by pohly** [comment]
FYI, current SecurityManager fails to compile with OE-core master:
https://travis-ci.org/01org/meta-intel-iot-security/jobs/100086771

```
| cd /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/common && /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/x86_64-linux/usr/bin/i586-oe-linux/i586-oe-linux-g++   -DAPI_VERSION=\"\" -DSMACK_ENABLED -Dsecurity_manager_commons_EXPORTS -m32 -march=i586  --sysroot=/home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/qemux86  -O2 -pipe -g -feliminate-unused-debug-types -fvisibility-inlines-hidden -g -std=c++0x -O2 -fPIC -isystem /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/qemux86/usr/include/db-util -isystem /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/qemux86/usr/include/dlog -isystem /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/qemux86/usr/include/glib-2.0 -isystem /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/qemux86/usr/lib/glib-2.0/include -isystem /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/qemux86/usr/include/cynara -I/home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/include -I/home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/common/include -I/home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/dpl/core/include -I/home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/dpl/log/include -I/home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/dpl/db/include -I/home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/qemux86/usr/include    -fPIC -Werror -Wall -Wextra -D_GNU_SOURCE -fPIC -fvisibility=default -o CMakeFiles/security-manager-commons.dir/privilege_db.cpp.o -c /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/common/privilege_db.cpp
| In file included from /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/common/include/message-buffer.h:30:0,
|                  from /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/common/message-buffer.cpp:25:
| /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/dpl/core/include/dpl/binary_queue.h:36:14: error: 'template<class> class std::auto_ptr' is deprecated [-Werror=deprecated-declarations]
|  typedef std::auto_ptr<BinaryQueue> BinaryQueueAutoPtr;
|               ^
| In file included from /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/qemux86/usr/include/c++/5.3.0/memory:81:0,
|                  from /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/dpl/core/include/dpl/binary_queue.h:28,
|                  from /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/common/include/message-buffer.h:30,
|                  from /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/work/i586-oe-linux/security-manager/1.0.2+gitAUTOINC+860305a595-r0/git/src/common/message-buffer.cpp:25:
| /home/travis/build/01org/meta-intel-iot-security/build/tmp-glibc/sysroots/qemux86/usr/include/c++/5.3.0/bits/unique_ptr.h:49:28: note: declared here
|    template<typename> class auto_ptr;
|                             ^
| cc1plus: all warnings being treated as errors
| make[2]: *** [src/common/CMakeFiles/security-manager-commons.dir/__/dpl/core/src/binary_queue.cpp.o] Error 1
```

I'll hold back working on that while you update to 1.1.0 - perhaps that version doesn't have that problem. But if it does, we need a fix (different compiler flags or source code patch) as part of the 1.1.0 PR, otherwise it won't build in TravisCI.

**Comment by pohly** [comment]
SecurityManager still present, but not used anymore, at least in Ostro OS.
